# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "custom_joinbed"
description: "Joins multiple methylation tab-separated files into a single file using the paste command."
keywords:
  - join
  - paste
  - methylation
  - epigenetics
  - tab
tools:
  - "custom":
      description: "The GNU Core Utilities are the basic file, shell and text manipulation utilities of the GNU operating system. These are the core utilities which are expected to exist on every operating system."
      homepage: "https://www.gnu.org/software/coreutils/"
      documentation: "https://www.gnu.org/software/coreutils/manual/"
      tool_dev_url: "https://git.savannah.gnu.org/cgit/coreutils.git"
      doi: ""
      licence: ["GPL"]
      identifier: null

input:
  - - sample_id:
        type: string
        description: "Sample identifier string"
    - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1' ]`
    - meth_tab:
        type: file
        description: "Input methylation tab-separated file(s)"
        pattern: "*.tab"

output:
  - joined_ch_tab:
      - - sample_id:
            type: string
            description: "Sample identifier string"
        - meta:
            type: map
            description: |
              Groovy Map containing sample information
              e.g. `[ id:'sample1' ]`
        - "${sample_id}_meth.tab*":
            type: file
            description: "Joined output file containing the combined methylation data"
            pattern: "*.tab*"

authors:
  - "@aaryanjaitly"
maintainers:
  - "@aaryanjaitly"
